#!/bin/bash -eu
set -o pipefail
{
#Shuffles and copies selfplay training from selfplay/ to shuffleddata/current/
#Should be run periodically.

ORIGINAL_ARGS=("$@")

if [[ $# -lt 3 ]]
then
    echo "Usage: $0 BASEDIR TMPDIR NTHREADS"
    echo "Currently expects to be run from within the 'python' directory of the KataGo repo, or otherwise in the same dir as shuffle.py."
    echo "BASEDIR containing selfplay data and models and related directories"
    echo "TMPDIR scratch space, ideally on fast local disk, unique to this loop"
    echo "NTHREADS number of parallel threads/processes to use in shuffle"
    exit 0
fi
BASEDIR="$1"
shift
TMPDIR="$1"
shift
NTHREADS="$1"
shift

#------------------------------------------------------------------------------

if command -v python3 >/dev/null 2>&1; then
  PYTHON=python3
else
  PYTHON=python
fi

BASEDIR="$(realpath "$BASEDIR")"
INPUT_ROOT="${KATAGO_SHUFFLE_INPUT_ROOT:-$BASEDIR/selfplay}"
SHUFFLED_ROOT="${KATAGO_SHUFFLE_OUTPUT_ROOT:-$BASEDIR/shuffleddata}"
INPUT_ROOT="$(realpath "$INPUT_ROOT")"
mkdir -p "$SHUFFLED_ROOT"
SHUFFLED_ROOT="$(realpath "$SHUFFLED_ROOT")"
if [[ "${KATAGO_SHUFFLE_GATE_BYPASS:-}" != "1" ]]
then
    exec "$PYTHON" -m katago.utils.shuffle_input_gate \
         --input-root "$INPUT_ROOT" \
         --state-file "$BASEDIR/shuffle-input-state.json" \
         --lock-file "$BASEDIR/shuffle-input.lock" \
         --output-root "$SHUFFLED_ROOT" \
         --force-after-seconds "${KATAGO_SHUFFLE_FORCE_AFTER_SECONDS:-0}" \
         -- "$0" "${ORIGINAL_ARGS[@]}"
fi

OUTDIR="${KATAGO_SHUFFLE_OUTPUT_ID:-$(date "+%Y%m%d-%H%M%S")}"
if [[ -z "$OUTDIR" || "$OUTDIR" == *"/"* || "$OUTDIR" == "." || "$OUTDIR" == ".." ]]
then
    echo "Invalid KATAGO_SHUFFLE_OUTPUT_ID: $OUTDIR" >&2
    exit 1
fi

mkdir -p "$SHUFFLED_ROOT"/"$OUTDIR".tmp
mkdir -p "$TMPDIR"/train
mkdir -p "$TMPDIR"/val

echo "Beginning shuffle at" $(date "+%Y-%m-%d %H:%M:%S")

if [[ -n "${SKIP_VALIDATE:-}" ]]
then
  (
      time $PYTHON ./shuffle.py \
           "$INPUT_ROOT"/ \
           -expand-window-per-row 0.4 \
           -taper-window-exponent 0.65 \
           -out-dir "$SHUFFLED_ROOT"/"$OUTDIR".tmp/train \
           -out-tmp-dir "$TMPDIR"/train \
           -approx-rows-per-out-file 70000 \
           -num-processes "$NTHREADS" \
           -keep-target-rows 20000000 \
           -only-include-md5-path-prop-lbound 0.00 \
           -only-include-md5-path-prop-ubound 1.00 \
           "$@" \
           2>&1 | tee "$SHUFFLED_ROOT"/"$OUTDIR".tmp/outtrain.txt &

      wait
  )
else
  # Randomly peels off 5% of files generated by selfplay as validation data
  (
      time $PYTHON ./shuffle.py \
           "$INPUT_ROOT"/ \
           -expand-window-per-row 0.4 \
           -taper-window-exponent 0.65 \
           -out-dir "$SHUFFLED_ROOT"/"$OUTDIR".tmp/val \
           -out-tmp-dir "$TMPDIR"/val \
           -approx-rows-per-out-file 70000 \
           -num-processes "$NTHREADS" \
           -keep-target-rows 20000000 \
           -only-include-md5-path-prop-lbound 0.95 \
           -only-include-md5-path-prop-ubound 1.00 \
           "$@" \
           2>&1 | tee "$SHUFFLED_ROOT"/"$OUTDIR".tmp/outval.txt &

      wait
  )
  (
      time $PYTHON ./shuffle.py \
           "$INPUT_ROOT"/ \
           -expand-window-per-row 0.4 \
           -taper-window-exponent 0.65 \
           -out-dir "$SHUFFLED_ROOT"/"$OUTDIR".tmp/train \
           -out-tmp-dir "$TMPDIR"/train \
           -approx-rows-per-out-file 70000 \
           -num-processes "$NTHREADS" \
           -keep-target-rows 20000000 \
           -only-include-md5-path-prop-lbound 0.00 \
           -only-include-md5-path-prop-ubound 0.95 \
           "$@" \
           2>&1 | tee "$SHUFFLED_ROOT"/"$OUTDIR".tmp/outtrain.txt &

      wait
  )
fi
#set +x

#Just in case, give a little time for nfs
sleep 10

# Shuffle no longer maintains a "current" directory, instead training script searches for latest dir
# rm -f "$BASEDIR"/shuffleddata/current_tmp
# ln -s $OUTDIR "$BASEDIR"/shuffleddata/current_tmp
# mv -Tf "$BASEDIR"/shuffleddata/current_tmp "$BASEDIR"/shuffleddata/current

mv "$SHUFFLED_ROOT"/"$OUTDIR".tmp "$SHUFFLED_ROOT"/"$OUTDIR"

# CLEANUP ---------------------------------------------------------------

#Among shuffled dirs older than 2 hours, remove all but the most recent 2 of them.
#This should be VERY conservative and allow plenty of time for the training to switch
#to newer ones as they get generated.
echo "Cleaning up any old dirs"
$PYTHON -W ignore "$(dirname "$0")/cleanup_old_dirs.py" "$SHUFFLED_ROOT/"

echo "Finished shuffle at" $(date "+%Y-%m-%d %H:%M:%S")
#Make a little space between shuffles
echo ""
echo ""

exit 0
}
